# Generated by Django 4.0.5 on 2022-07-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_options_homepage_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttechnologiesorderable',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['sort_order']},
        ),
    ]
